name: activator
description: Compoza.NET Activator. This app allows to control Wordpress plugins.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.5+8

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  i18n_extension:
  intl:
  provider:
  http:
  validators:
  firebase_core:
  cloud_firestore:
  firebase_auth:
  google_sign_in:
  flutter_facebook_auth:
  flutter_signin_button:
  twitter_login:
  sign_in_with_apple:
  crypto:
  hive:
  hive_flutter:
  package_info:

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/locales/