name: activator
description: Compoza.NET Activator. This app allows to control Wordpress plugins.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path_provider:
  provider: ^4.3.3
  http: ^0.12.2
  get_it: ^5.0.6

  shared_preferences: ^0.5.12+4
  validators: ^2.0.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/activator_logo.png
    - assets/images/user_unknown.png
    - assets/images/drawer_background.png